### PR TITLE
No ccds cuts

### PR DESCRIPTION
**Pull request by kaylanb**
@dstndstn 

This PR removes all instances of CCD cuts from legacypipe. Either the column "ccd_cuts" is in the ccds table(s) and those cuts are applied, or no cuts are applied. I ran `runbrick_test.py` and most of the tests passed until this one failed. See below. Any ideas?

The error log is here: [error.txt](https://github.com/legacysurvey/legacypipe/files/1458751/error.txt)

-------------
runbrick.py starting at 2017-11-09T10:16:22.549344
Args: ['--brick', '2173p350', '--zoom', '100', '200', '100', '200', '--no-wise', '--force-all', '--no-write', '--survey-dir', 'mzlsbass3', '--outdir', 'out-mzlsbass3']

Slurm cluster: none
Job id: none
Array task id: none

Got survey: LegacySurveyData: dir mzlsbass3, out out-mzlsbass3

-----------

### CODE REVIEW

**Comment by moustakas** [comment]
I've been following the thread on-list.  One question: will the code be backwards-compatible with the set of CCDs used in DR4/DR5?  Because I'm definitely rerunning Tractor and would like everything to be as reproducible as possible --

**Comment by kaylanb** [comment]
I'm not sure it makes sense to be backwards compatible with "old" DRs. Really the only way to rerun a previous DR is to checkout its tag and use all the input files that when into it. That's how I'm approaching image simulations by rerunning DR3 (for eBOSS) and DR5. 

@dstndstn ?

**Comment by dstndstn** [comment]
Yeah, that's my take too.  In this case, we should be able to make this backwards-compatible by swapping in the annotated-ccds file for the survey-ccds files (possibly renaming a column) because the annotated ones have a column saying whether they passed the photometric cuts.

**Comment by dstndstn** [comment]
Turns out that unit test was pretty much getting skipped in the master branch (all CCDs were getting cut due to the HDU_MISMATCH cut -- in the test cases the data are all in HDU 1), so this just points out a problem with the test cases.

**Pull request merged**
