### PR TITLE
Refactor ps1cat

### PR DESCRIPTION
**Pull request by dstndstn**
(pulling out a superclass HealpixedCatalog; add GaiaCatalog using it.)

I kept the ps1 API, but have not tested it.

### CODE REVIEW

**Comment by dstndstn** [comment]
@moustakas , could you please take a look and merge if it looks okay to you?

**Comment by moustakas** [comment]
The code looks OK, although I haven't fully tested the changes because I'm in python purgatory/hell on NERSC trying to switch over to conda, and I don't have the Gaia catalog mirrored on my local machine yet.  We could go ahead and merge if this is urgent and then open up a new issue if we encounter any problems when we start building zeropoint files (on my radar for mid-October, once the MzLS data have been re-reduced).   @dstndstn please advise or perhaps @kaylanb can do some quick tests if he's set up right now.

**Comment by kaylanb** [comment]
Oct. 7 I should be re-running some DR3 bricks to ensure I reproduce Dustin's before I move onto DR4. I can do this then.

**Comment by dstndstn** [comment]
@moustakas @kaylanb Any update on this?

**Comment by kaylanb** [comment]
@moustakas @dstndstn Lets merge it. I'll pull these gaiacat.py and ps1cat.py into legacy-zeropoints branch before merging legacy-zeropoints

**Comment by moustakas** [comment]
It doesn't look like this was ever merged -- should I clean it up and merge or did something else happen elsewhere?

**Comment by kaylanb** [comment]
HI John,

It was never merged and nothing elsewhere. Merging may affect
legacy_zeropoints here
<https://github.com/legacysurvey/legacypipe/blob/master/py/legacyccds/legacy_zeropoints.py#L774>,
but I can work on my zeropoints updates in a separate branch. So merge if
you think it is ready!

Best,
Kaylan

**Comment by moustakas** [comment]
There are conflicts in `legacyanalysis.ps1cat` that need to be resolved and I'm afraid the code has diverged so far that I'm not quite sure what is new in this branch and what is new in master and should be kept.  @dstndstn or @kaylanb one of you needs to take a look.

And then we need to do a much better job (my fault on this one!) of reviewing and merging much faster.  We should also strive to clean up our stale branches...

**Comment by kaylanb** [comment]
Hi John,

Yeah that sounds about right. I can make sure to delete old branches next
week. For the differences from this branch to master, can you or @dstndstn
list the scripts that depend on ps1cat.py and how they use it?

-Kaylan

**Comment by moustakas** [comment]
Looks like `apphot-decam`, `compare-to-ps1`, `gaiacat`, `psf_residuals`, `refit-wcs`, `run-one-chip`, and `zpdiffs` from `legacyanalysis` and `legacy-zeropoints` from `legacyccds` (obviously).

I don't know offhand which of these are imperative and can be fixed later (other than `legacy-zeropoints`).  We need to do a general cleanup of this whole product....

**Comment by dstndstn** [comment]
I fixed the merge conflicts, please let me know if this breaks anything!

**Pull request merged**
