### PR TITLE
add MoG model for ELG colors

### PR DESCRIPTION
**Pull request by moustakas**
This PR adds a mixture-of-Gaussian parameterization of the grz colos for z~1 ELGs for use with the simulations code.  The associated notebook shows the details:
  https://github.com/legacysurvey/legacypipe/blob/elgcolorcolor/doc/nb/calib-color-color.ipynb

@kaylanb please take a look and merge if this is satisfactory.

### CODE REVIEW

**Comment by kaylanb** [comment]
@moustakas ,

Looks great. How is the input file (elg_templates_v2.0.fits) made?  e.g. from relevant cuts to /project/projectdirs/desi/target/analysis/deep2/v1.0/deep2egs-oii.fits.gz? Do you think we could restrict the gr, rz plane to the ELG Target Selection box + some padding (say +0.5 mag) for scatter in/out?

**Comment by moustakas** [comment]
The ```elg_templates_v2.0.fits``` file comes from building the basis templates for the DESI pipeline development (see ```desihub/desisim```) and I used it as a convenience because it had the DECaLS photometry already synthesized (based on modeling the full spectral energy distribution of each object).  We can make the mapping between the DEEP2 photometry and the synthesized photometry a bit more transparent if you want by spinning off the relevant bits of (IDL - yikes!) code, but it won't make a big difference on the final results.

If you want to restrict your simulations to DESI *selected* ELGs, then I propose you simply draw grz colors from the MoG basis, apply the relevant color-cuts --
  https://github.com/desihub/desitarget/blob/master/py/desitarget/cuts.py#L50
and then repeat until you have the sized sample you want.

**Comment by kaylanb** [comment]
@moustakas ,

Okay, do I understand correctly?
- using the redshift, OII fluxes, CFHTLS photometry, etc from DEEP2 _Field 1_ (EGS), `desihub/desisim` created synthetic spectra, integrated over DECAM grz bands, and these grz fluxes were stored in `elg_templates_v2.0.fits`
- it is Field 1, so we have associated halflight radii and sersic n

Also, what exactly is required (e.g. redshift, OII fluxes, broadband photometry) to make the synthetic spectra? I could not find that in desisim docs

**Comment by kaylanb** [comment]
A minor detail: Is `elg_templates_v2.0.fits` is over the full DEEP2 region?  

I made plots of GALFIT sersic n vs. halflight radius ([galfit hi](http://portal.nersc.gov/project/desi/users/kburleigh/decals_sim/elgs/elgs_size_hi.png) and [galfit_low](http://portal.nersc.gov/project/desi/users/kburleigh/decals_sim/elgs/elgs_size_low.png)) for DEEP2 Field 1, and I don't have the density of points especially at low sersic as in the notebook:
https://github.com/legacysurvey/legacypipe/blob/elgcolorcolor/doc/nb/calib-color-color.ipynb

**Comment by kaylanb** [comment]
Please DONT delete this branch. I'm closing the PR for the next week while I add LRG, QSO in addition to STAR, ELG

**Pull request closed without merging**
