### PR TITLE
Update sweeps to reflect data model

### PR DESCRIPTION
**Pull request by geordie666**
This PR updates the code to generate the sweeps (and external files) to hopefully reflect the DR9 data model.

### CODE REVIEW

**Comment by geordie666** [comment]
@dstndstn: I've added Christophe's requested `LC` (light-curve) WISE columns to the sweeps as part of this PR.

But, beyond that, here are some things that I've gleaned about the new data model from propagating the Tractor files to the sweeps in this PR. It would be good to have confirmation from you that these changes are intended. Particularly as regards `TYPE`:

- `FRACDEV`, `FRACDEV_IVAR`, `SHAPEDEV_X` and `SHAPEEXP_X` have been deprecated and replaced by `SHAPE_X`. This is intended, and is due to removing objects of type `COMP`.
- The `TYPE` column is now of datatype `S3` instead of the `S4` that was used for previous releases. I don't know if this is an intentional change to the data model? Also, _some_ of the Tractor files retain `('TYPE', 'S4')`. I believe these correspond to (any) Tractor files that contain an object of type `DUP `. This is almost certainly unintentional. So, I think either the `DUP ` entries need the extra, ending, space dropped, are we need to enforce `('TYPE', 'S4')` for everything when writing the `TYPE` column.

**Comment by dstndstn** [comment]
Heh, good catch with the "DUP ".  D'oh.

**Comment by geordie666** [comment]
@dstndstn: So, for DR9, is the `TYPE` column definitely meant to be `S3`? If so, I think you can go ahead and merge this PR.

For `dr9c`, which has mixed `TYPE` formats, `generate-sweep-files.py` will just need to be run with the `--ignore_errors` option.

**Comment by moustakas** [comment]
Merging this now so at least we'll have the proper code in place for `dr9d`, although who knows what changes DR9 itself will bring!  Thanks @geordie666.

**Pull request merged**
