### PR TITLE
ability to inject synthetic stars into the images

### PR DESCRIPTION
**Pull request by kaylanb**
python test/runbrick_test.py completes but, at the very end, complains about the backend not being set properly: no $DISPLAY environment variable

### CODE REVIEW

**Comment by moustakas** [comment]
It would be great to get your eyes on this, @dstndstn, especially since some changes were made to the primary pipeline code (specifically ```legacypipe.runbrick``` and ```legacypipe.common```.  Although the Travis tests pass (although coveralls is strangely failing...), we want to make sure we haven't broken any key part of the production code.

**Comment by dstndstn** [comment]
Coveralls is just "failing" because the code coverage percentage went down -- fewer lines of code are hit by the coverage tests here
https://github.com/legacysurvey/legacypipe/blob/master/.travis.yml#L55
You can ignore this.  However, going forward it *would* be good to have some tests of the decals_sim code -- if you can produce a command-line test that runs quickly (say, under a minute), you can add it here:
https://github.com/legacysurvey/legacypipe/blob/master/py/test/runbrick_test.py
and then your code will be tested on each commit... that way, if I break your code I will be forced to fix it right away, rather than you finding out the next time you try to run it :)

**Comment by dstndstn** [comment]
- I don't understand the need for the added code in coadds.py -- as far as I can see, this is just repackaging sims_xy from the tim into the "C.T" catalog that is returned by coadds.py.  Normally, the "C.T" table contains per-source values that are looked-up in the maps produced by coadds.py.  In the case of sims_xy I don't see why that code should be in coadds.py.

- in runbrick.py, I think I would rewrite
'''
if 'sims_image' in tims[0].__dict__:
'''
as
'''
if hasattr(tims[0], 'sims_image'):
'''
but that's just stylistic.

Also there, rather than calling *make_coadds* two more times, you could probably do the simpler
'''
sims_coadd,nil = quick_coadds(tims, bands, targetwcs, images=[tim.sims_image for tim in tims])
image_coadd,nil = quick_coadds(tims, bands, targetwcs, images=[tim.data - tim.sims_image for tim in tims])
'''

**Comment by kaylanb** [comment]
---> I don't understand the need for the added code in coadds.py
I'm removing the added code. I wanted the option to show how big the simulated image stamps were for an individual star or galaxy in a coadd. But this is a debugging thing so not needed.
---> hasattr()
done
---> quick_coadd()
awesome!, done

**Comment by kaylanb** [comment]
@dstndstn , I definitely want to add tests via 
https://github.com/legacysurvey/legacypipe/blob/master/py/test/runbrick_test.py
but are these quantitative (either measured fluxes are within 0.1 % of what you know they should be OR not)? or just qualitative (it still runs to completion)?

**Comment by dstndstn** [comment]
Hi Kaylan,
The existing tests are just "runs to completion", but quantitative tests would absolutely be an improvement!

**Comment by dstndstn** [comment]
Okay, so I'm going to merge this, and any additional test case improvements can go straight to master.
Good stuff!

**Pull request merged**
