### PR TITLE
add unwise_modelsky_dir to output header(s) and as optional input to run_brick

### PR DESCRIPTION
**Pull request by moustakas**
Addresses #320.  Still testing; not quite ready to merge.

Note that previously this directory variable was called `background_dir`, which I changed to `unwise_modelsky_dir` to match the other unWISE directories (static + time-resolved stacks).

### CODE REVIEW

**Comment by moustakas** [comment]
This is good to go; should be a non-controversial merge.

Adds a couple new header cards about the WISE maps (and changes a little bit of logging)--
```
UNWISSKY= '/global/homes/i/ioannis/dr8b/decam/calib/wise/modelsky'
DEPNAM16= 'unwise_modelsky'
DEPVER16= '/global/homes/i/ioannis/dr8b/decam/calib/wise/modelsky'
```
*But*.  Do we want to resolve the symbolic link to the background maps?  So instead of reading `/global/homes/i/ioannis/dr8b/decam/calib/wise/modelsky`, which is a soft-link, it would read `/global/homes/i/ioannis/dr8b/decam/calib/wise/modelsky` (using `os.path.realpath`).

Any strong opinions?

**Comment by dstndstn** [comment]
I would vote we not resolve symlinks -- Aaron often uses symlinks within the data directories, eg, when things need to live on projecta for space reasons.  You should fix your environment variables! :)

**Comment by dstndstn** [comment]
Hah, I see I was too slow with my comment!

**Comment by moustakas** [comment]
@dstndstn I'm not proposing to resolve the `UNWISE_COADDS_DIR` and `UNWISE_COADDS_TIMERESOLVED_DIR` variables, just the `modelsky` one.  

In production, we have
```
ls -ld calib/wise/modelsky
lrwxrwxrwx 1 desiproc cosmo 66 Mar 16 07:47 calib/wise/modelsky -> /global/project/projectdirs/cosmo/work/wise/unwise_catalog/dr1/mod
```
and so with the current code `/global/project/projectdirs/cosmo/work/wise/unwise_catalog/dr1/mod` is what would get recorded in the header.  

Is that acceptable?

**Comment by dstndstn** [comment]
Sure :)

**Pull request merged**
