### PR TITLE
Only compute sig1 in ccds table

### PR DESCRIPTION
**Pull request by dstndstn**

### CODE REVIEW

**Comment by dstndstn** [comment]
for #351

**Comment by moustakas** [comment]
It's mildly shocking that we've been carrying around this inconsistency between the sigma measured in the CCDs files vs what was being recomputed and used in Tractor processing, so thank you for this PR.  Good to know that the sigma now matches the documentation (i.e., nanomaggies vs ADUish)!

Let's be sure we've got all the factors of gain, exposure time, zpt etc., correct for all three cameras by correlating sigma with depth and other diagnostics once we have a largish sample in-hand.

Otherwise, changes look good, feel free to merge.

**Comment by moustakas** [comment]
I'll note that this PR makes the pipeline completely incompatible with old calibration/CCDs files, since the "units" of the sigma threshold used to detect sources has now changed.  It's fine, I just had to discover the consequence!

**Comment by dstndstn** [comment]
ohhhh yeah, I did not consider that.  Could keep the old behavior -- where the tims recomputed sig1 from the local invvar -- enabled with a flag.  We will soon have all the DR8 calibs and CCDs files, so hopefully you and others can switch to those...?

**Comment by moustakas** [comment]
Forward!

**Pull request merged**
