### PR TITLE
replace old --run entries with decam / 90prime-mosaic ones

### PR DESCRIPTION
**Pull request by dstndstn**

### CODE REVIEW

**Comment by dstndstn** [comment]
For #293

**Comment by moustakas** [comment]
Can you give examples of usage, e.g., for how we should run DR8 from the same top-level directory?

**Comment by dstndstn** [comment]
```
python runbrick.py --run decam --release 8000 --brick 1340p330
python runbrick.py --run 90prime-mosaic --release 8001 --brick 1340p330
```

But I'm thinking about making the release default be based on the --run.

**Comment by dstndstn** [comment]
Now just
```
python runbrick.py --run decam --brick 1340p330
python runbrick.py --run 90prime-mosaic --brick 1340p330
```
sets the default RELEASE.

**Pull request merged**
