### PR TITLE
Outlier masks: write to multi-extension FITS; run in parallel

### PR DESCRIPTION
**Pull request by dstndstn**

### CODE REVIEW

**Comment by moustakas** [comment]
I can test this in a bit, or you can merge and we can fix any issues in a separate PR.  Your call.

**Comment by dstndstn** [comment]
Do we want to start merging the other PRs also?

**Comment by moustakas** [comment]
> Do we want to start merging the other PRs also?

I'm testing this PR now, so please hold off.  The other PRs are uncontroversial except #263, which will require https://github.com/legacysurvey/legacyzpts/pull/50 for the calibs (unless we also solve #270 as well). But by all means, let's get these merged in.

**Comment by moustakas** [comment]
Here's the wreck that is much of dr8b:
http://legacysurvey.org/viewer-dev?ra=137.4869&dec=33.1950&zoom=13&layer=dr8b-decam&bricks
and here's this branch on brick `1374p332` -- gorgeous!
legacysurvey-1374p332-image

**Comment by moustakas** [comment]
Other lovely improvements:  the code writes out just five files, four `jpg`s and a MEF file.  E.g., in this brick, the file `outlier-mask-1374p332.fits.fz` has 43 HDUs, one for each (portion) of the CCD touching this brick--

```python
  file: metrics/137/outlier-mask-1374p332.fits.fz
  mode: READONLY
  extnum hdutype         hduname[v]
  0      IMAGE_HDU       
  1      IMAGE_HDU       decam-635542-S26
  2      IMAGE_HDU       decam-625315-S25
  3      IMAGE_HDU       decam-829476-N23
  4      IMAGE_HDU       decam-829474-N28
  5      IMAGE_HDU       decam-635542-S29
  6      IMAGE_HDU       decam-829474-N18
  7      IMAGE_HDU       decam-635542-S27
  8      IMAGE_HDU       decam-829476-N24
  9      IMAGE_HDU       decam-829474-N19
  10     IMAGE_HDU       decam-625315-S26
  11     IMAGE_HDU       decam-635542-S30
  12     IMAGE_HDU       decam-829476-N18
  13     IMAGE_HDU       decam-730744-S25
  14     IMAGE_HDU       decam-625315-S29
  15     IMAGE_HDU       decam-829474-N24
  16     IMAGE_HDU       decam-535115-N18
  17     IMAGE_HDU       decam-624881-S26
  18     IMAGE_HDU       decam-624490-S25
  19     IMAGE_HDU       decam-829475-N23
  20     IMAGE_HDU       decam-624881-S29
  21     IMAGE_HDU       decam-624881-S27
  22     IMAGE_HDU       decam-829475-N24
  23     IMAGE_HDU       decam-535115-N19
  24     IMAGE_HDU       decam-624490-S26
  25     IMAGE_HDU       decam-624881-S30
  26     IMAGE_HDU       decam-829475-N18
  27     IMAGE_HDU       decam-730097-S25
  28     IMAGE_HDU       decam-624490-S29
  29     IMAGE_HDU       decam-535115-N24
  30     IMAGE_HDU       decam-535892-N18
  31     IMAGE_HDU       decam-625671-S25
  32     IMAGE_HDU       decam-603116-S26
  33     IMAGE_HDU       decam-830630-N23
  34     IMAGE_HDU       decam-603116-S29
  35     IMAGE_HDU       decam-603116-S27
  36     IMAGE_HDU       decam-830630-N24
  37     IMAGE_HDU       decam-535892-N19
  38     IMAGE_HDU       decam-625671-S26
  39     IMAGE_HDU       decam-830630-N18
  40     IMAGE_HDU       decam-626013-S25
  41     IMAGE_HDU       decam-625671-S29
  42     IMAGE_HDU       decam-535892-N24
```

**Comment by moustakas** [comment]
And here's the image of masked pixels.
outliers-masked-1374p332

**Pull request merged**
