### PR TITLE
Create sweep files

### PR DESCRIPTION
**Pull request by rainwoodman**
To do list: 
- [ ] decide a location for the files.
- [X] Verifying the results: single rank and 48 ranks gives the same result on sweep file 014.
- [X] Benchmarks on Edison: single rank < 20 bricks per second at beginning of the run. 48 ranks ~ 255 bricks per second near the end of the run on DR1. Always ~ 100 seconds enumerating the tractor files.
- [X] Match against SDSS DR12 five data sets.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Note that I've left the infrastructure for MPI in the edison job script.

Also do we want the obj matching in the same PR?

**Comment by moustakas** [comment]
This looks great to me, but @dstndstn should sign off as well.  DR2 is nearly done, at which point the file locations should be finalized.

The spectroscopic object matching can easily go into this PR if that'd be more convenient.  Is the object-matching code designed to run on the sweeps?  There are two files I think we should match against -- the spAll file and the QSO-specific redshift catalog.

**Comment by rainwoodman** [comment]
The last bunch of commits were for RA-stripe based sweep files which were discussed at the (workshop?) refer to my comments on Issue #69  for a summary.

**Comment by rainwoodman** [comment]
I added a preliminary script (match-boss-catalogue.py) to do the matching. 

- threshold for 'matching' is set to 1 arcsec;
- Mirrors the directory tree of the input.
- files are renamed to decals-boss-*.fits (or .hdf5)
- unmatched object has 'SURVEY' = 'N/A'
- DR2p is at /global/cscratch1/sd/yfeng1/sandbox/sweep-dr2p-boss-dr12/

**Comment by rainwoodman** [comment]
Let's decided the final location of files in this PR. 

- Shall I rename these files into legacypipe directory?
- Alternatively, do we want to keep the scripts for these 'derived' files in a different directory (e.g. ``legacyderived``)?

Suggestions from @dstndstn  / @moustakas ?

**Comment by dstndstn** [comment]
I would say that any scripts used to produce our primary and derived data
products (including sweeps) could go in legacypipe ... but I don't feel
strongly about it.  I don't know if there will be a *lot* of 'derived'
products to require a new directory for them.

**Comment by rainwoodman** [comment]
I have moved the files to legacypipe. 

- There is a new 'internal' subpackage for the internal guts I used to identify files and parallelism. 
- The python scripts (which are otherwise self contained) are dropped to bin directory for now.

**Comment by weaverba137** [comment]
If the sweeps are *done*, that would imply that they were built off of this branch, rather than off of a tagged version of legacypipe.  That means that any version information in the sweep file headers is invalid.

If the sweeps are *not done* you can ignore this comment.

**Comment by rainwoodman** [comment]
Neither do I have a strong opinion on the location of the files. I will merge this in so that we can potentially tag this and maintain a consistent tag of the sweep files with code for the future (or dr2 if it isn't yet too late).

**Comment by moustakas** [comment]
Unfortunately, it was pointed out in some recent correspondence on desi-imaging that the sweep files do not contain everything we may want from the Tractor catalogs (e.g., the measured galaxy ellipticities). 

If it's possible, I'd like to propose, therefore, that we create a new version of the sweep files which include *all* the measurements from the parent Tractor catalogs.  @rainwoodman would it be possible to read a single catalog on-the-fly to get the data model, or does it need to be specified ahead of time?

@weaverba137 Is it within the realm of possibility to add a sweep/2.1 directory to DR2 once this is done (and thoroughly vetted)?

Thanks, and this one is on me -- I thought the sweeps had everything we would ever need, but it didn't take long of playing with the catalogs to discover this shortcoming.

**Comment by djschlegel** [comment]
John-  This particular request was for just a tiny bit of sky (COSMOS), in which case one can just
use the couple of brick files.  -D

**Comment by rainwoodman** [comment]
It is not hard to dump and rewrite the full DR2 schema. However, the main issue is that a single sweep file may grow too big if we keep all measurements -- and we will need smaller per-sweep area. -- I recall the fits format could not handle bigger than 4GB files?

I would propose we just add new columns and call that 2.1, and keep bumping up the version numbers as new columns are identified. In the meanwhile we will also remove the columns that have been identified to be not very useful. Just keep bumping up the version numbers -- that's what the version number is for. This will eventually stablize before DR3.

**Comment by moustakas** [comment]
@djschlegel This particular request was just over the COSMOS field, but it's definitely worth having all the measurements for the full DR2.

@rainwoodman Could you generate version 2.1 sweeps with all the Tractor measurements?  If the file sizes get unwieldy we can move to smaller block in ra,dec (but only if necessary).

**Comment by djschlegel** [comment]
John-  The sweep files already contain nearly 50% of the bytes from the Tractor catalogs,
506 of 1164 bytes.  If we were to push this to the majority of the bytes, then the question
gets turned around to what bytes are being excluded.

**Comment by weaverba137** [comment]
I have to agree with @djschlegel here.  In SDSS, the sweep files have a data volume that is only about 10% of the full photometric catalog.  That's what you should be aiming for.  Otherwise why not just use the full catalog?

**Comment by moustakas** [comment]
OK, let's hold off then.  I thought the sweeps were closer to already being nearly full Tractor catalogs (the convenience being the bigger chunks of sky), but we probably don't want to grow much more than the 50% of the bytes we're already carrying forward.

**Pull request merged**
