### PR TITLE
add --unwise-coadds flag to write out FITS and JPEGs of WISE tiles overlapping

### PR DESCRIPTION
**Pull request by dstndstn**
- no model images yet

### CODE REVIEW

**Comment by dstndstn** [comment]
Models requires this new tractor commit:
https://github.com/dstndstn/tractor/commit/91c0b02bc2a01902923fcb4b11d8c14bcd12309e

**Comment by moustakas** [comment]
Thanks @dstndstn.

With the following call to `runbrick` I get 202x202 pixel optical images but 19x19 pixel unWISE images.  Is it crazy to grossly oversample the unWISE images so they have the sample pixel scale as the optical images by default?  I note that 202/19 is roughly the ratio of the native pixel scales of the two datasets, 2.65/0.262.

```bash 
python runbrick.py --radec 240.8291314166443 3.279053011143758 --width 202 \
  --height 202 --pixscale 0.262 --threads 18 --unwise-coadds
```

However, I also get this crash indicating that `tractor.ceres` does not exist.  Here I've git cloned the master branch of tractor and added it to my personal `PYTHONPATH` with 
```bash
git clone https://github.com/dstndstn/tractor.git                                                                              
cd tractor/                                                                                                                    
make                                                                                                                           
python setup.py install --prefix=/global/cscratch1/sd/ioannis/repos/build                                                                          
```

```python
[snip]
Reading /global/projecta/projectdirs/cosmo/work/wise/outputs/merge/neo4/e009/240/2405p030/unwise-2405p030-w2-n-u.fits.gz
Reading /global/cscratch1/sd/ioannis/repos/build/lib/python3.6/site-packages/wise/wise-psf-avg.fits
Broadening PSF: from GaussianMixturePSF: amps=(0.50069285264069419, 0.34100864476817461, 0.13439912296940892), means=(0.0, 0.0, 0.0, 0.0, 0.0, 0.0), var=(0.80497933224871177, 0.0, 0.0, 0.80497933224871177, 1.769306668019893, 0.0, 0.0, 1.769306668019893, 14.340555455911327, 0.0, 0.0, 14.340555455911327)
Broadened PSF: GaussianMixturePSF: amps=(0.50069285264069419, 0.34100864476817461, 0.13439912296940892), means=(0.0, 0.0, 0.0, 0.0, 0.0, 0.0), var=(0.86164759109771749, 0.0, 0.0, 0.86164759109771749, 1.8938608326175561, 0.0, 0.0, 1.8938608326175561, 15.350089832829989, 0.0, 0.0, 15.350089832829989)
Read image with shape (21, 20)
37 within the image + margin
36 strictly within the image
Reading /global/projecta/projectdirs/cosmo/work/wise/outputs/merge/neo4/e007/240/2405p030/unwise-2405p030-w2-n-m.fits.gz
unwise_forcedphot failed:
Traceback (most recent call last):
  File "/global/cscratch1/sd/ioannis/repos/legacypipe/py/legacypipe/runbrick.py", line 2914, in _unwise_phot
    W = unwise_forcedphot(wcat, tiles, use_ceres=wise_ceres, **kwargs)
  File "/global/cscratch1/sd/ioannis/repos/build/lib/python3.6/site-packages/wise/forcedphot.py", line 165, in unwise_forcedphot
    wantims=wantims, **kwa)
  File "/global/cscratch1/sd/ioannis/repos/build/lib/python3.6/site-packages/tractor/engine.py", line 235, in optimize_forced_photometry
    return self.optimizer.forced_photometry(self, **kwargs)
  File "/global/cscratch1/sd/ioannis/repos/build/lib/python3.6/site-packages/tractor/optimize.py", line 123, in forced_photometry
    Nsky=Nsky, mindlnp=mindlnp, shared_params=shared_params, **kwargs)
  File "/global/cscratch1/sd/ioannis/repos/build/lib/python3.6/site-packages/tractor/ceres_optimizer.py", line 39, in _optimize_forcedphot_core
    x = self._ceres_forced_photom(tractor, result, *args, **kwargs)
  File "/global/cscratch1/sd/ioannis/repos/build/lib/python3.6/site-packages/tractor/ceres_optimizer.py", line 221, in _ceres_forced_photom
    from tractor.ceres import ceres_forced_phot
ModuleNotFoundError: No module named 'tractor.ceres'
Trying without Ceres...
[snip]
```

**Comment by decalsobserver** [comment]
gotta "make ceres" in the tractor directory.  this requires a ton of
libraries; I can send you instructions

**Comment by dstndstn** [comment]
(is it actually crashing, or does it go on to try without ceres, as it claims it is going to do?)

**Comment by dstndstn** [comment]
# For Tractor "make ceres":
export SUITESPARSE_LIB_DIR="${SuiteSparse_PREFIX}/lib"
export BLAS_LIB="${blas_LIBS_CC}"
if [ $NERSC_HOST == "cori" ]; then
module load eigen3
fi
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:$EIGEN3_DIR/share/pkgconfig
export PYTHON_CONFIG=python3-config

**Comment by dstndstn** [comment]
right, by default it creates the WISE coadds at 2.75"/pix.  10x oversampling seems a little excessive :)  Were you thinking for the FITS, JPEG, or both?

**Comment by moustakas** [comment]
`make ceres` seems to complete OK, although there's a non-catastrophic warning about the `gflags` package missing (see below).  Nevertheless, I still get a `ModuleNotFoundError: No module named '_ceres'` when doing the WISE forced photometry.  However, as you suspected, the code completes just fine, so I'm just intended to run with the `--no-wise-ceres` switch.

I think this is ready to be merged.  It *may* be fun to provide a `pixscale-wise` option (defaulting to 2.75 arcsec) but it shouldn't block this PR.

One final thing I'll note is that there are no inverse variance images or bad-pixel masks written out for W1-W4 (which is fine).

Here's the relevant bit of the output from compiling Tractor:
```
make -C tractor mpf
make[1]: Entering directory '/global/cscratch1/sd/ioannis/repos/tractor/tractor'
python setup-mpf.py build_ext --inplace
running build_ext
building '_mp_fourier' extension
swigging mp_fourier.i to mp_fourier_wrap.c
swig -python -o mp_fourier_wrap.c mp_fourier.i
C compiler: gcc -pthread -B /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/numpy/core/include -I/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/include/python3.6m -c'
extra options: '-g -std=c99'
gcc -pthread -shared -B /global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/compiler_compat -L/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib -Wl,-rpath=/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/mp_fourier_wrap.o -o /global/cscratch1/sd/ioannis/repos/tractor/tractor/_mp_fourier.cpython-36m-x86_64-linux-gnu.so -g
make[1]: Leaving directory '/global/cscratch1/sd/ioannis/repos/tractor/tractor'
ioannis@cori06:~/scratch/repos/tractor% make ceres
make -C tractor ceres
make[1]: Entering directory '/global/cscratch1/sd/ioannis/repos/tractor/tractor'
Package gflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `gflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gflags' found
Package gflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `gflags.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gflags' found
swig -python -c++ -I/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/numpy/core/include  -I/global/common/cori/software/eigen3/3.3.3/include/eigen3  ceres.i
ceres.i:335: Warning 401: Nothing known about base class 'ceres::IterationCallback'. Ignored.
g++ -Wall -fPIC -O0 -g -c ceres_wrap.cxx -I/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/include/python3.6m -I/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/include/python3.6m -I/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/numpy/core/include  -I/global/common/cori/software/eigen3/3.3.3/include/eigen3  -I/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/aux/include
[snip]
```

**Comment by moustakas** [comment]
Travis tests passed while coveralls failed.  Assuming this is OK, @dstndstn let's get this feature in master.

**Comment by dstndstn** [comment]
coveralls is just complaining because there is 1% more code not touched by tests

**Pull request merged**
