### PR TITLE
code to process large galaxies in Legacy Survey imaging

### PR DESCRIPTION
**Pull request by moustakas**
This PR contains work from last summer to do custom photometry of the large galaxies.  Most of the changes to the code *not* in `legacyanalysis.large-galaxies.py` were made to resolve conflicts, so this shouldn't affect the production code.

However, Travis tests are failing for reasons that I don't think are related to this PR.

If we could merge this soon I'd like to pick up development where I left off in a new branch.

### CODE REVIEW

**Comment by moustakas** [comment]
@dstndstn Can you take a peak at the failing tests?  It looks like they're ~all related to the Tractor dependency.

**Comment by moustakas** [comment]
`legacypipe.image` has a 'MyHybridPsf` Class which may have been a hack last summer. Maybe removing that is the way to go, assuming `HybridPSF` is now incorporated in Tractor?

**Comment by dstndstn** [comment]
Yes, that looks right, the master legacypipe image.py class uses the tractor's HybridPixelizedPSF class for this.

**Comment by moustakas** [comment]
Thanks @dstndstn!

**Pull request merged**
