### PR TITLE
Resolve sources that are in the LSLGA *and* Gaia

### PR DESCRIPTION
**Pull request by dstndstn**
This also makes significant changes to the way to set maximum galaxy radii!

### CODE REVIEW

**Comment by moustakas** [comment]
Related issues are #286, #300, #302, and #309.

I tested this branch on `NGC0497`.  Previous results (from `dr8b`) are here:
http://legacysurvey.org/viewer-dev?ra=20.5985&dec=-0.8752&zoom=16&layer=dr8b-decam-model&gaia-dr2&dr8b-decam

New results are illustrated here:
ngc0497

Previously for this piece of sky we ended up (in the center) with the large galaxy, two r=15 point sources, and one r=17 Gaia source.

With this branch, in the output Tractor catalog we still end up with three sources within 1 arcsec of each other: the Gaia star (with no flux *or* type but all the Gaia catalog entries unchanged---good), a point source (PSF), and the large galaxy (a COMP), e.g.,
```
        ra                 dec          type    flux_g  gaia_phot_g_mean_mag ref_cat
       deg                 deg                nanomaggy                             
     float64             float64       bytes4  float32        float32         bytes2
------------------ ------------------- ------ --------- -------------------- -------
20.599155074363384 -0.8752381377098114   PSF   106.5214                  0.0        
20.599103179745736  -0.875101067757659   COMP   4309.49                  0.0      L2
20.599068720567686 -0.8752128669582195              0.0             17.52175      G2
```
So this is pretty good, but (1) I think we need some way to flag the Gaia sources that weren't allowed to be fitted (or have really good documentation); and (2) work a bit harder on source detection near the centers of "known" objects like these large galaxies.

I'm going to test on a few more large galaxies, but in the meantime additional comments are welcome.

**Comment by djschlegel** [comment]
If we're happy with this behavior, then it's identifiable with TYPE="".  I might prefer a value like TYPE="NONE" rather than an empty string.

**Comment by dstndstn** [comment]
legacysurvey-0206m010-image
legacysurvey-0206m010-model
legacysurvey-0206m010-resid

**Comment by dstndstn** [comment]
With these fixes -- primarily, reading the FPACK data to find the truncation error, to avoid clipping the center of the galaxy, which generated duplicate sources in the donut surrounding the clipped center -- there are two sources in the core -- one the Gaia source, with TYPE = "DUP" (duplicate), and one the LSLGA source with TYPE="COMP".

**Comment by dstndstn** [comment]
This is likely to fix #315 also (I just checked the first one and indeed it does).

**Comment by dstndstn** [comment]
Fixes the first #300 example too.

**Comment by dstndstn** [comment]
In the branch ignore-cr-streak, I tried ignoring both the CR and Streak DQ codes.  It looks good for this galaxy!

legacysurvey-0206m010-image
legacysurvey-0206m010-model
legacysurvey-0206m010-resid

**Comment by dstndstn** [comment]
outliers

**Comment by moustakas** [comment]
Outstanding.  Merging now and will continue to test on master.

**Pull request merged**
