### PR TITLE
'run to completion' test for decals_sim

### PR DESCRIPTION
**Pull request by kaylanb**
@dstndstn ,

I added this "run to completion" test for decals_sim
#https://github.com/legacysurvey/legacypipe/blob/addtest_decals_sim/py/test/runbrick_test.py#L42

It inserts 2 stars in a 50''x50'' region and checks that the correct files are written; however, it takes **13 minutes** to run.  I also call it with bash() as I couldn't get the analogous main() call to work. Any ideas to improve it?

Thanks,
Kaylan

### CODE REVIEW

**Comment by kaylanb** [comment]
@moustakas, 

I also deleted the decals_sim_works branch :)

**Comment by dstndstn** [comment]
Hi,

In decals_sim.py : main, you still need to add all the arguments to the parser when args != None... maybe that's why you couldn't get calling main() to work.

To work with the Travis-CI system, all the data needed by your test must exist in the repository.  But we don't want to include a huge amount of data, so can you:

(actually, try using the same --brick and --zoom and --survey-dir as the "testcase3" test, that will be way easier.  but leaving the instructions here anyway)

- use decals_sim.py --zoom to zoom in on a tiny subimage (say, 100x100 pixels)
- run runbrick.py on that same brick and --zoom region
- then run legacyanalysis/create_testcase.py, passing it (a) the coadd/*/*/*-ccds.fits file written by runbrick.py; (b) an output directory; and (c) the brickname.  This script will cut out just the 100x100 pixel regions in all the images, and also gather all the calib and other files required, and write a subset of the bricks and CCDs files to that output directory.  It creates a minimal self-contained LEGACY_SURVEY_DIR that can be used for testing.  This *should* be small enough (say, at most 1-2 MB) to check into the repository.  The test/mzlsbass and test/testcase3 directories were created this way.  (For that matter, maybe you could use the same --brick and --zoom as testcase3...)?
- adjust your decals_sim.py call to use that directory as your --survey-dir

cheers,
--dustin

**Comment by kaylanb** [comment]
Thanks! It now uses testcase3 data, called by importing main(), and completes in 44 sec. I think we are ready to merge. And Travis looks happy.

**Comment by dstndstn** [comment]
The Travis build failed because we don't have galsim...
https://travis-ci.org/legacysurvey/legacypipe/builds/144188006#L744

Galsim is... a bit of a pain to build, isn't it?  tmv and stuff?

It's a bit of a pain adding stuff to the Travis environment because you have to do it by changing .travis.yml, commit&push, and then seeing what breaks.

**Comment by kaylanb** [comment]
Yes hard to install but I assumed travis uses hpcp modulees
module load galsim-hpcp
Can travis do that?

**Comment by decalsobserver** [comment]
Nope, Travis doesn't know about hpcp, or modules.  hpcp is pretty much a
Ted / NERSC thing; Travis is a third-party service.

**Comment by kaylanb** [comment]
Is there a way to do two independent tests, one ran by travis and another that say, submits a 2 min job to debug to handle stuff like decals_sim?

**Comment by kaylanb** [comment]
@dstndstn , @moustakas ,

I've given this some more thought and I don't think a "testing mode" is what we want. Even if we have code that saves the simulated postage stamps and reads, adds them back in correctly, there are still many critical assert() statements that rely on galsim. For instance, making sure pixelized psfs have 7'' aperture fluxes in agreement with requested fluxes.

Do you agree?

If Ted is around in the next few weeks I can get his help to build galsim for Travis. That should significantly reduce the pain of doing it!

**Comment by kaylanb** [comment]
Sorry, I should have read more about Travis. We'll manually run our own test for now until the time investment to build galsim is worth it. 

Closing this PR because going to push a fix_flux PR that has the same test code.

**Pull request closed without merging**
